language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g gitbook-cli
  - gitbook install
script: gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: _book 
